name: Ruffd5bf055afc09
on:
  push:
    branches: [master]
  pull_request:
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          version: 0.1.8
      - uses: chartboost/ruff-action@v1
        with:
          args: format --check
          version: 0.1.8